# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "919e88ca96685994550e0a9bc9236584"
name = "Planet Beauty Inventory AI"
handle = "focused-policy-app-6"
application_url = "https://pb-inventory-ai-olive.vercel.app/"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_inventory,read_inventory,read_locations,read_orders"

[auth]
redirect_urls = [
  "https://pb-inventory-ai-olive.vercel.app/auth/callback",
  "https://pb-inventory-ai-olive.vercel.app/auth/callback/"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
