# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "919e88ca96685994550e0a9bc9236584"
name = "focused-policy-app"
handle = "focused-policy-app-6"
application_url = "https://missile-thing-ball-wed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,read_locations"

[auth]
redirect_urls = ["https://missile-thing-ball-wed.trycloudflare.com/auth/callback", "https://missile-thing-ball-wed.trycloudflare.com/auth/shopify/callback", "https://missile-thing-ball-wed.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
