# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbe7b20b3e77c1bb27f095d5757253a9"
name = "Planet Beauty AI Inventory"
handle = "planet-beauty-ai-inventory"
application_url = "https://vertical-departmental-screening-patches.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = ["https://vertical-departmental-screening-patches.trycloudflare.com/auth/callback", "https://vertical-departmental-screening-patches.trycloudflare.com/auth/shopify/callback", "https://vertical-departmental-screening-patches.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
