# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "919e88ca96685994550e0a9bc9236584"
name = "Planet Beauty Inventory AI"
handle = "focused-policy-app-6"
application_url = "https://pb-inventory-ai-olive.vercel.app/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://pb-inventory-ai-olive.vercel.app/auth/callback",
  "https://pb-inventory-ai-olive-pbaichatbots-projects.vercel.app/auth/callback"
]

[pos]
embedded = true

[app_preferences]
url = "https://pb-inventory-ai-olive.vercel.app/"
